apiVersion: v1
kind: Pod
metadata:
  name: pod-env12
spec:
  containers:
    - name: env-var-container
      image: nginx:1.7.9
      env:
        - name: testenv
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: database